### ISSUE TITLE
adjustWhenViewWillAppear 在cell中什么时候调用此方法？

### ISSUE THREAD

**Issue by Minozmin** [bestDew/ZKCycleScrollViewDemo-OC#1]
您好，我想请问一下，我在cell里面添加ZKCycleScrollView，请问adjustWhenViewWillAppear这个方法在什么时候调用比较合适呢?

**Comment by bestDew** [comment]
同样是在你 tableview/collectionView 或者是 tableviewController/collectionViewController 的 
-viewWillAppear：方法中调用。

假定 BannerCell 是你添加 ZKCycleScrollView 的 cell 类，然后：
1.将 ZKCycleScrollView 暴露在你自定义 BannerCell 的 .h 文件中供外部访问；
2.- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    for (UITableViewCell *cell in _tableView.visibleCells) {
       if ([cell isMemberOfClass:[BannerCell class]]) {
            BannerCell *bannerCell = (BannerCell *)cell;
             [bannerCell.cycleScrollView adjustWhenViewWillAppear];
       }
    }
}

当然这只是示例代码，只提供一个解决思路，具体实现细节还要根据你的需求去完善。

**Comment by bestDew** [comment]
> 您好，我想请问一下，我在cell里面添加ZKCycleScrollView，请问adjustWhenViewWillAppear这个方法在什么时候调用比较合适呢?

同样是在你 tableview/collectionView所在的 viewController 或者是 tableviewController/collectionViewController 的
-viewWillAppear：方法中调用。

假定 BannerCell 是你添加 ZKCycleScrollView 的 cell 类，然后：
1.将 ZKCycleScrollView 暴露在你自定义 BannerCell 的 .h 文件中供外部访问；
2.- (void)viewWillAppear:(BOOL)animated {
[super viewWillAppear:animated];

for (UITableViewCell *cell in _tableView.visibleCells) {
   if ([cell isMemberOfClass:[BannerCell class]]) {
        BannerCell *bannerCell = (BannerCell *)cell;
         [bannerCell.cycleScrollView adjustWhenViewWillAppear];
   }
}
}

当然这只是示例代码，只提供一个解决思路，具体实现细节还要根据你的需求去完善。

**Comment by Minozmin** [comment]
我现在就是这样处理的，谢谢

**Comment by BeingCode** [comment]
有什么更好一点的方法，谢谢
