### ISSUE TITLE
iOS11 crash 

### ISSUE THREAD

**Issue by kwhuang** [bestDew/ZKCycleScrollViewDemo-OC#13]
**- (void)scrollViewWillBeginDecelerating:(UIScrollView *)scrollView
{
    NSInteger index = [self currentIndex] + _indexOffset;
    UICollectionViewScrollPosition position = [self scrollPosition];
    NSIndexPath *indexPath = [NSIndexPath indexPathForItem:index inSection:0];
    [_collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:position animated:YES]; // 数组越界崩溃
    _indexOffset = 0;
}**

**Comment by bestDew** [comment]
> **- (void)scrollViewWillBeginDecelerating:(UIScrollView _)scrollView { NSInteger index = [self currentIndex] + _indexOffset; UICollectionViewScrollPosition position = [self scrollPosition]; NSIndexPath _indexPath = [NSIndexPath indexPathForItem:index inSection:0]; [_collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:position animated:YES]; // 数组越界崩溃 _indexOffset = 0; }__

最新版已经修复了，更新下
