### ISSUE TITLE
pod 不了项目

### ISSUE THREAD

**Issue by Minozmin** [bestDew/ZKCycleScrollViewDemo-OC#14]
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/4/9/0/FWCycleScrollView/2.1.2/FWCycleScrollView.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Connection refused - connect(2) for "raw.githubusercontent.com" port 443)

**Comment by ZTzhaotian** [comment]
me too
