### ISSUE TITLE
ios14 不滚动

### ISSUE THREAD

**Issue by ijeffery3** [bestDew/ZKCycleScrollViewDemo-OC#15]

**Comment by ZeMingXianSheng** [comment]
@ijeffery3 请问你怎么解决的，how to fix it。

**Comment by ZeMingXianSheng** [comment]
if (position == UICollectionViewScrollPositionCenteredHorizontally) {
        [_collectionView setContentOffset:CGPointMake((CGRectGetWidth(self.bounds) + _flowLayout.minimumLineSpacing) * indexPath.item, 0) animated:YES];
    } else {
        [_collectionView setContentOffset:CGPointMake(0, (CGRectGetHeight(self.bounds) + _flowLayout.minimumLineSpacing) * indexPath.item) animated:YES];
    }
手动计算。
