### ISSUE TITLE
只有一张图片的时候会crash

### ISSUE THREAD

**Issue by Minozmin** [bestDew/ZKCycleScrollViewDemo-OC#2]
- (void)reloadData
{
    [self removeTimer];
    [UIView performWithoutAnimation:^{
        会崩在这个动画这里performBatchUpdates
        [_collectionView performBatchUpdates:^{
            [_collectionView reloadSections:[NSIndexSet indexSetWithIndex:0]];
        } completion:^(BOOL finished) {
            [self configuration];
            if (_loadCompletion) _loadCompletion();
        }];
    }];
}

**Comment by Minozmin** [comment]
第一次加载添加了ZKCycleScrollView的cell能正常显示，当我向下滑动这个cell滑出屏幕时，我再向上滑动，当这个cell要出现在屏幕上的时候就会crash，你的demo现在没有列表，你可以我放到列表上测试一下

**Comment by bestDew** [comment]
> * (void)reloadData
>   {
>   [self removeTimer];
>   [UIView performWithoutAnimation:^{
>   会崩在这个动画这里performBatchUpdates
>   [_collectionView performBatchUpdates:^{
>   [_collectionView reloadSections:[NSIndexSet indexSetWithIndex:0]];
>   } completion:^(BOOL finished) {
>   [self configuration];
>   if (_loadCompletion) _loadCompletion();
>   }];
>   }];
>   }

感谢反馈，这个 bug 已修复，建议 clone 最新代码，或者用以下代码直接替换原实现：
- (void)reloadData
{
    [self removeTimer];
    [UIView performWithoutAnimation:^{
        [_collectionView reloadData];
    }];
    [_collectionView performBatchUpdates:nil completion:^(BOOL finished) {
        [self configuration];
        if (_loadCompletion) _loadCompletion();
    }];
}

**Comment by bestDew** [comment]
> 第一次加载添加了ZKCycleScrollView的cell能正常显示，当我向下滑动这个cell滑出屏幕时，我再向上滑动，当这个cell要出现在屏幕上的时候就会crash，你的demo现在没有列表，你可以我放到列表上测试一下

这个 bug 我这边刚写了个 demo 没有复现，可以把崩溃日志发出来看下嘛？

**Comment by Minozmin** [comment]
*** Assertion failure in -[UICollectionViewAnimation initWithView:viewType:finalLayoutAttributes:startFraction:endFraction:animateFromCurrentPostion:deleteAfterAnimation:customAnimations:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.93.8/UICollectionView_InternalHelperClasses.m:247

**Comment by kwhuang** [comment]
当滚动cell上面需要计算字符串size的时候，首个计算的字符串是第二个cell的数据的size
