### ISSUE TITLE
首次加载最前面的cell没有刷新出来

### ISSUE THREAD

**Issue by IvanYue** [bestDew/ZKCycleScrollViewDemo-OC#3]
首次加载最前面的cell没有加载出来，滚动一下，就又正常了。是因为：在 configuration 方法中没有获取到_numberOfItems 的值。一直是0不会滚动。
修改后的代码：
`- (void)configuration
{
    [self addTimer];
    [self updatePageControl];
    
    if ([_dataSource respondsToSelector:@selector(numberOfItemsInCycleScrollView:)]) {
        _numberOfItems = [_dataSource numberOfItemsInCycleScrollView:self];
        if (_numberOfItems > 1)_numberOfItems += 4;
    }
    
    if (_numberOfItems < 2) return;
    
    [self layoutIfNeeded];
    
    UICollectionViewScrollPosition position = [self scrollPosition];
    NSIndexPath *indexPath = [NSIndexPath indexPathForItem:2 inSection:0];
    [_collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:position animated:NO];
}`
或者直接暴露出_numberOfItems最好。滚动前需要加 [self layoutIfNeeded]; 不然_numberOfItems有值会滚动代码失效。不能贴图，只能口述，有些乱。

**Comment by bestDew** [comment]
> 首次加载最前面的cell没有加载出来，滚动一下，就又正常了。是因为：在 configuration 方法中没有获取到_numberOfItems 的值。一直是0不会滚动。
> 修改后的代码：
> `- (void)configuration
> {
> [self addTimer];
> [self updatePageControl];
> 
> ```
> if ([_dataSource respondsToSelector:@selector(numberOfItemsInCycleScrollView:)]) {
>     _numberOfItems = [_dataSource numberOfItemsInCycleScrollView:self];
>     if (_numberOfItems > 1)_numberOfItems += 4;
> }
> 
> if (_numberOfItems < 2) return;
> 
> [self layoutIfNeeded];
> 
> UICollectionViewScrollPosition position = [self scrollPosition];
> NSIndexPath *indexPath = [NSIndexPath indexPathForItem:2 inSection:0];
> [_collectionView scrollToItemAtIndexPath:indexPath atScrollPosition:position animated:NO];
> ```
> 
> }`
> 或者直接暴露出_numberOfItems最好。滚动前需要加 [self layoutIfNeeded]; 不然_numberOfItems有值会滚动代码失效。不能贴图，只能口述，有些乱。

感谢反馈！我这边没复现这个问题，但是优化了可能会引起上述 bug 的地方，详见最新代码，如果还会出现上述 bug， 烦请再告知下
