### ISSUE TITLE
最近一直出现这个，能麻烦看下原因么？

### ISSUE THREAD

**Issue by Minozmin** [bestDew/ZKCycleScrollViewDemo-OC#6]
2019-07-15 17:29:18.075247+0800 Haoshiqi[1556:514178] The behavior of the UICollectionViewFlowLayout is not defined because:
2019-07-15 17:29:18.075365+0800 Haoshiqi[1556:514178] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2019-07-15 17:29:18.076445+0800 Haoshiqi[1556:514178] The relevant UICollectionViewFlowLayout instance is <ZKCycleScrollViewFlowLayout: 0x1032b7600>, and it is attached to <UICollectionView: 0x1040d2a00; frame = (0 0; 375 160); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2809dbf30>; layer = <CALayer: 0x2807fe940>; contentOffset: {0, 0}; contentSize: {375, 160}; adjustedContentInset: {0, 0, 0, 0}> collection view layout: <ZKCycleScrollViewFlowLayout: 0x1032b7600>.
2019-07-15 17:29:18.076562+0800 Haoshiqi[1556:514178] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

**Comment by bestDew** [comment]
> 2019-07-15 17:29:18.075247+0800 Haoshiqi[1556:514178] The behavior of the UICollectionViewFlowLayout is not defined because:
> 2019-07-15 17:29:18.075365+0800 Haoshiqi[1556:514178] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
> 2019-07-15 17:29:18.076445+0800 Haoshiqi[1556:514178] The relevant UICollectionViewFlowLayout instance is <ZKCycleScrollViewFlowLayout: 0x1032b7600>, and it is attached to <UICollectionView: 0x1040d2a00; frame = (0 0; 375 160); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2809dbf30>; layer = <CALayer: 0x2807fe940>; contentOffset: {0, 0}; contentSize: {375, 160}; adjustedContentInset: {0, 0, 0, 0}> collection view layout: <ZKCycleScrollViewFlowLayout: 0x1032b7600>.
> 2019-07-15 17:29:18.076562+0800 Haoshiqi[1556:514178] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

能把轮播图设置的相关代码发来看看嘛？

**Comment by Minozmin** [comment]
//这是在自定义cell里面的实现
@implementation HSQSwiperWidgetCell

- (void)awakeFromNib {
    [super awakeFromNib];
    // Initialization code
    
    self.backgroundColor = [UIColor whiteColor];
    [self setupUI];
    [self.scrollView registerCellNib:[UINib nibWithNibName:reuseHSQImageViewCell bundle:[NSBundle mainBundle]] forCellWithReuseIdentifier:reuseHSQImageViewCell];
}

- (void)layoutSubviews
{
    [super layoutSubviews];
    
    self.scrollView.frame = CGRectMake(0, 0, CGRectGetWidth(self.frame), CGRectGetHeight(self.frame));
    if (![self.indexCell isFullScreen]) {
        self.scrollView.itemSize = CGSizeMake(CGRectGetWidth(self.frame) - 30, CGRectGetHeight(self.frame));
    }
    
    self.pageControl.frame = CGRectMake(0, CGRectGetHeight(self.frame) - 15, CGRectGetWidth(self.frame), 15);
}

#pragma mark - init ui

- (void)setupUI
{
    [self addSubview:self.scrollView];
    [self addSubview:self.pageControl];
}

- (ZKCycleScrollView *)scrollView
{
    if (!_scrollView) {
        _scrollView = [[ZKCycleScrollView alloc] init];
        _scrollView.delegate = self;
        _scrollView.dataSource = self;
        _scrollView.itemSpacing = 5;
        _scrollView.hidesPageControl = YES;
    }
    return _scrollView;
}

- (HSQPageControl *)pageControl
{
    if (!_pageControl) {
        _pageControl = [[HSQPageControl alloc] init];
        _pageControl.dotColor = [UIColor whiteColor];
        _pageControl.currentColor = HSQColorFB0438;
    }
    return _pageControl;
}

#pragma mark - data

- (void)setData:(DMIndexCell *)data delegate:(id)delegate
{
    self.indexCell = data;
    self.datas = data.datas;
    
    //只有一张图片时
    if (self.datas.count == 1) {
        self.pageControl.numberOfPages = 0;
        self.scrollView.autoScroll = NO;
    }else {
        self.pageControl.numberOfPages = self.indexCell.isDots ? self.datas.count : 0;
        self.scrollView.autoScroll = self.indexCell.autoScroll;
        self.scrollView.autoScrollInterval = self.indexCell.autoScrollInterval;
    }
    
    [self.scrollView reloadData];
}

#pragma mark - ZKCycleScrollViewDelegate

- (NSInteger)numberOfItemsInCycleScrollView:(ZKCycleScrollView *)cycleScrollView
{
    return self.datas.count;
}

- (UICollectionViewCell *)cycleScrollView:(ZKCycleScrollView *)cycleScrollView cellForItemAtIndex:(NSInteger)index
{
    BaseCollectionViewCell *cell = [cycleScrollView dequeueReusableCellWithReuseIdentifier:reuseHSQImageViewCell forIndex:index];
    [cell setData:self.datas[index] delegate:self];
    return cell;
}

- (void)cycleScrollView:(ZKCycleScrollView *)cycleScrollView didSelectItemAtIndex:(NSInteger)index
{
    NSString *link = self.datas[index].link;
    [HSQClickTracker event:self.indexCell.moduleId index:index attributes:@{kHSQTrackerLink: link, kHSQTrackerUserGroup: self.indexCell.flowCode}];
    [HSQSchema openURLString:self.datas[index].link];
}

- (void)cycleScrollView:(ZKCycleScrollView *)cycleScrollView didScrollFromIndex:(NSInteger)fromIndex toIndex:(NSInteger)toIndex
{
    self.pageControl.currentIndex = toIndex;
}

@end

//在vc中设置了这个
- (void)viewWillAppear:(BOOL)animated
{
     [self.bannerCell.scrollView adjustWhenViewWillAppear];
}

**Comment by bestDew** [comment]
> //这是在自定义cell里面的实现
> @implementation HSQSwiperWidgetCell
> 
> * (void)awakeFromNib {
>   [super awakeFromNib];
>   // Initialization code
>   self.backgroundColor = [UIColor whiteColor];
>   [self setupUI];
>   [self.scrollView registerCellNib:[UINib nibWithNibName:reuseHSQImageViewCell bundle:[NSBundle mainBundle]] forCellWithReuseIdentifier:reuseHSQImageViewCell];
>   }
> * (void)layoutSubviews
>   {
>   [super layoutSubviews];
>   self.scrollView.frame = CGRectMake(0, 0, CGRectGetWidth(self.frame), CGRectGetHeight(self.frame));
>   if (![self.indexCell isFullScreen]) {
>   self.scrollView.itemSize = CGSizeMake(CGRectGetWidth(self.frame) - 30, CGRectGetHeight(self.frame));
>   }
>   self.pageControl.frame = CGRectMake(0, CGRectGetHeight(self.frame) - 15, CGRectGetWidth(self.frame), 15);
>   }
> 
> #pragma mark - init ui
> 
> * (void)setupUI
>   {
>   [self addSubview:self.scrollView];
>   [self addSubview:self.pageControl];
>   }
> * (ZKCycleScrollView *)scrollView
>   {
>   if (!_scrollView) {
>   _scrollView = [[ZKCycleScrollView alloc] init];
>   _scrollView.delegate = self;
>   _scrollView.dataSource = self;
>   _scrollView.itemSpacing = 5;
>   _scrollView.hidesPageControl = YES;
>   }
>   return _scrollView;
>   }
> * (HSQPageControl *)pageControl
>   {
>   if (!_pageControl) {
>   _pageControl = [[HSQPageControl alloc] init];
>   _pageControl.dotColor = [UIColor whiteColor];
>   _pageControl.currentColor = HSQColorFB0438;
>   }
>   return _pageControl;
>   }
> 
> #pragma mark - data
> 
> * (void)setData:(DMIndexCell *)data delegate:(id)delegate
>   {
>   self.indexCell = data;
>   self.datas = data.datas;
>   //只有一张图片时
>   if (self.datas.count == 1) {
>   self.pageControl.numberOfPages = 0;
>   self.scrollView.autoScroll = NO;
>   }else {
>   self.pageControl.numberOfPages = self.indexCell.isDots ? self.datas.count : 0;
>   self.scrollView.autoScroll = self.indexCell.autoScroll;
>   self.scrollView.autoScrollInterval = self.indexCell.autoScrollInterval;
>   }
>   [self.scrollView reloadData];
>   }
> 
> #pragma mark - ZKCycleScrollViewDelegate
> 
> * (NSInteger)numberOfItemsInCycleScrollView:(ZKCycleScrollView *)cycleScrollView
>   {
>   return self.datas.count;
>   }
> * (UICollectionViewCell *)cycleScrollView:(ZKCycleScrollView *)cycleScrollView cellForItemAtIndex:(NSInteger)index
>   {
>   BaseCollectionViewCell *cell = [cycleScrollView dequeueReusableCellWithReuseIdentifier:reuseHSQImageViewCell forIndex:index];
>   [cell setData:self.datas[index] delegate:self];
>   return cell;
>   }
> * (void)cycleScrollView:(ZKCycleScrollView *)cycleScrollView didSelectItemAtIndex:(NSInteger)index
>   {
>   NSString *link = self.datas[index].link;
>   [HSQClickTracker event:self.indexCell.moduleId index:index attributes:@{kHSQTrackerLink: link, kHSQTrackerUserGroup: self.indexCell.flowCode}];
>   [HSQSchema openURLString:self.datas[index].link];
>   }
> * (void)cycleScrollView:(ZKCycleScrollView *)cycleScrollView didScrollFromIndex:(NSInteger)fromIndex toIndex:(NSInteger)toIndex
>   {
>   self.pageControl.currentIndex = toIndex;
>   }
> 
> @EnD
> 
> //在vc中设置了这个
> 
> * (void)viewWillAppear:(BOOL)animated
>   {
>   [self.bannerCell.scrollView adjustWhenViewWillAppear];
>   }

这里应该是你轮播图的容器 cell 的布局造成了 itemSize 大于 ZKCycleScrollView 的 size，控制台才打印错误信息的，具体你可以自己调试下……

另外建议把轮播图控件添加在 cell 的 contentView 上，然后基于 contentView 的 frame 去设置轮播图控件的 frame。

**Comment by Minozmin** [comment]
//cell1
(lldb) po self.scrollView
<ZKCycleScrollView: 0x1036a53c0; frame = (0 0; 375 160); layer = <CALayer: 0x281890020>>

(lldb) po self.scrollView.itemSize
(width = 345, height = 160)

(lldb) po self
<HSQSwiperWidgetCell: 0x1035d5f00; baseClass = UICollectionViewCell; frame = (0 0; 375 160); clipsToBounds = YES; opaque = NO; layer = <CALayer: 0x281894320>>

//cell2
(lldb) po self.scrollView
<ZKCycleScrollView: 0x1035e5900; frame = (0 0; 375 214.547); animations = { position=<CABasicAnimation: 0x2818c8400>; bounds.origin=<CABasicAnimation: 0x2818db020>; bounds.size=<CABasicAnimation: 0x2818dbce0>; }; layer = <CALayer: 0x281885440>>

(lldb) po self.scrollView.itemSize
(width = 345, height = 214.546875)

(lldb) po self
<HSQSwiperWidgetCell: 0x1035e3f40; baseClass = UICollectionViewCell; frame = (0 460; 375 214.547); clipsToBounds = YES; opaque = NO; animations = { backgroundColor=<CABasicAnimation: 0x2818b3780>; }; layer = <CALayer: 0x2818b3540>>

我这边是有两个cell，，两个cell的高度不一样，但ZKCycleScrollView的itemsize都没有大于size呀，只有一个cell的时候是不会打印这些的
